name: Generate Index

on:
  pull_request:

jobs:
  build:
    name: "Generate index and readme"
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.27.1
      with:
        php-version: '8.2'

    - name: Check committer
      id: check
      run: |
        COMMITTER=$(git log -1 --pretty=format:'%ae')
        echo "COMMITTER=$COMMITTER" >> $GITHUB_ENV
    
    - name: Run script
      run: php .github/workflows/scripts/generate_index.php
      if: env.COMMITTER != 'action@github.com'
      
    - name: Commit and push if it changed
      run: | 
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update index.json and README.md" || exit 0
        git push
